

HF_MAPPING = {
    "CommitPackFT": "commitpack_ft",
    "Dolly 15k": "dolly_15k",
    "Open Assistant v2": "open_assistant_v2",
    "Open Assistant OctoPack": "octopack_oa",
    "Open Assistant": "open_assistant",
    "OIG": "oig",
    "Anthropic HH-RLHF": "rlhf_anthropic_hh",
    "Flan Collection (Super-NaturalInstructions)":  "flan_sni",
    "Flan Collection (P3)": "flan_p3",
    "Flan Collection (Flan 2021)": "flan_2021",
    "Tasksource Symbol-Tuning": "tasksource_symboltuning",
    "Tasksource Instruct": "tasksource_instruct",
    "Flan Collection (Chain-of-Thought)": "flan_cot",
    "HelpSteer": "helpsteer",
    "Aya Dataset": "aya_dataset",
    "AgentInstruct": "agentinstruct",
    "xP3x": "xp3x",
    "Flan Collection (Dialog)": "flan_dialog",
    "Joke Explanation": "joke_explanation",
    "StarCoder Self-Instruct": "starcoder_selfinstruct",
    "DialogStudio": "dialogstudio",
}