name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          version: 23.1.0
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      # Install package and deps so third-party packages are sorted
      - name: Install Dependencies and Package
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
      - uses: isort/isort-action@master
